#!/usr/bin/env bash


ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."


# exit on error
set -e


cd "$ROOT_DIR"


# build docs
cd docs
# make html
sphinx-build -M html source ../build/docs

# open
cd ..
open build/docs/html/index.html
