#!/usr/bin/env bash


ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."


# exit on error
set -e


cd "$ROOT_DIR"


# build docs
cd doc
# make html
sphinx-build -M html source ../build/doc

# open
cd ..
open build/doc/html/index.html
